# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_regis', '0002_auto_20170224_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='trips',
            field=models.ManyToManyField(related_name='Group', to='login_regis.User'),
        ),
    ]
