# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_regis', '0004_auto_20170224_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='travel_from',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='travel',
            name='travel_to',
            field=models.CharField(max_length=255),
        ),
    ]
