# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_regis', '0005_auto_20170224_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='trips',
        ),
        migrations.AddField(
            model_name='travel',
            name='join',
            field=models.ManyToManyField(blank=True, null=True, related_name='group', to='login_regis.User'),
        ),
        migrations.AddField(
            model_name='travel',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='login_regis.User'),
            preserve_default=False,
        ),
    ]
