# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_regis', '0006_auto_20170303_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='join',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
