# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_regis', '0007_auto_20170305_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='friend_id',
            field=models.ManyToManyField(related_name='_user_friend_id_+', to='login_regis.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.ManyToManyField(related_name='_user_user_id_+', to='login_regis.User'),
        ),
    ]
